CREATE TABLE FUNCIONARIO (
    CODIGOFUNCIONARIO int NOT NULL,
    NOME varchar(90) NOT NULL,
    CPF char(15) NULL,
    SEXO char(1) NOT NULL,
    DTNASCIMENTO date NOT NULL,
    SALARIO real NULL,
    CONSTRAINT FUNCIONARIO_pk PRIMARY KEY (CODIGOFUNCIONARIO));
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (1, 'ROBERTA SILVA BRASIL', '82998', 'F', '20/02/1980',7000);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (2, 'MARIA SILVA BRASIL', '9876', 'F', '20/09/1988',9500);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (3,'GABRIELLA PEREIRA LIMA','32998','F','20/02/1990',6000);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (4, 'MARCOS PEREIRA BRASIL','9999', 'M','20/02/1999',6000);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO) VALUES (5, 'HEMERSON SILVA BRASIL','9111','M','20/12/1992',4000);