-- Tabela REGIAO
CREATE TABLE REGIAO (
    ID_REGIAO NUMERIC(7) PRIMARY KEY,
    NOME VARCHAR(40)
);

-- Tabela DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
    ID NUMERIC(7) PRIMARY KEY,
    NOME VARCHAR(40),
    ID_REGIAO NUMERIC(7) NOT NULL,
    FOREIGN KEY (ID_REGIAO) REFERENCES REGIAO(ID_REGIAO)
);

-- Tabela EMPREGADO
CREATE TABLE EMPREGADO (
    ID NUMERIC(7) PRIMARY KEY,
    PRIM_NOME VARCHAR(20),
    ULT_NOME VARCHAR(20),
    CARGO VARCHAR(30),
    CPF CHAR(11),
    ID_DEPTO NUMERIC(7) NOT NULL,
    ID_GERENTE NUMERIC(7),
    FOREIGN KEY (ID_DEPTO) REFERENCES DEPARTAMENTO(ID),
    FOREIGN KEY (ID_GERENTE) REFERENCES EMPREGADO(ID)
);

-- Tabela CLIENTE
CREATE TABLE CLIENTE (
    ID NUMERIC(7) PRIMARY KEY,
    NOME VARCHAR(40),
    VENDEDOR NUMERIC(7) NOT NULL,
    FOREIGN KEY (VENDEDOR) REFERENCES EMPREGADO(ID)
);
