-- Tabela REGIAO
CREATE TABLE REGIAO (
    ID_REGIAO NUMERIC(7) PRIMARY KEY,
    NOME VARCHAR(40)
);

-- Tabela DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
    ID NUMERIC(7) PRIMARY KEY,
    NOME VARCHAR(40),
    ID_REGIAO NUMERIC(7) NOT NULL,
    FOREIGN KEY (ID_REGIAO) REFERENCES REGIAO(ID_REGIAO)
);

-- Tabela EMPREGADO
CREATE TABLE EMPREGADO (
    ID NUMERIC(7) PRIMARY KEY,
    PRIM_NOME VARCHAR(20),
    ULT_NOME VARCHAR(20),
    CARGO VARCHAR(30),
    CPF CHAR(11),
    ID_DEPTO NUMERIC(7) NOT NULL,
    ID_GERENTE NUMERIC(7),
    FOREIGN KEY (ID_DEPTO) REFERENCES DEPARTAMENTO(ID),
    FOREIGN KEY (ID_GERENTE) REFERENCES EMPREGADO(ID)
);

-- Tabela CLIENTE
CREATE TABLE CLIENTE (
    ID NUMERIC(7) PRIMARY KEY,
    NOME VARCHAR(40),
    VENDEDOR NUMERIC(7) NOT NULL,
    FOREIGN KEY (VENDEDOR) REFERENCES EMPREGADO(ID)
);



--  INSERÇÃO DE DADOS 

-- Populando REGIAO
INSERT INTO REGIAO (ID_REGIAO, NOME) VALUES (1, 'Sudeste');
INSERT INTO REGIAO (ID_REGIAO, NOME) VALUES (2, 'Sul');

-- Populando DEPARTAMENTO
INSERT INTO DEPARTAMENTO (ID, NOME, ID_REGIAO) VALUES (10, 'Vendas', 1);
INSERT INTO DEPARTAMENTO (ID, NOME, ID_REGIAO) VALUES (20, 'Financeiro', 2);

-- Populando EMPREGADO
INSERT INTO EMPREGADO (ID, PRIM_NOME, ULT_NOME, CARGO, CPF, ID_DEPTO, ID_GERENTE) VALUES (100, 'João', 'Silva', 'Gerente', '12345678901', 10, NULL);
INSERT INTO EMPREGADO (ID, PRIM_NOME, ULT_NOME, CARGO, CPF, ID_DEPTO, ID_GERENTE) VALUES (101, 'Maria', 'Souza', 'Vendedor', '23456789012', 10, 100);

-- Populando CLIENTE
INSERT INTO CLIENTE (ID, NOME, VENDEDOR) VALUES (1000, 'Empresa Alpha', 101);
INSERT INTO CLIENTE (ID, NOME, VENDEDOR) VALUES (1001, 'Empresa Beta', 101);
